services:
#    dressme.example:
#        class: fb\DressmeBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
services:
   app_bundle.service.listener:
        class: fb\DressmeBundle\Listener\LoadDataListener
        tags:
            - { name: 'kernel.event_listener', event: 'fullcalendar.set_data', method: loadData }