prestation_index:
    path:     /
    defaults: { _controller: "DressmeBundle:Prestation:index" }
    methods:  GET

prestation_show:
    path:     /{id}/show
    defaults: { _controller: "DressmeBundle:Prestation:show" }
    methods:  GET

prestation_new:
    path:     /new
    defaults: { _controller: "DressmeBundle:Prestation:new" }
    methods:  [GET, POST]

prestation_edit:
    path:     /{id}/edit
    defaults: { _controller: "DressmeBundle:Prestation:edit" }
    methods:  [GET, POST]

prestation_delete:
    path:     /{id}/delete
    defaults: { _controller: "DressmeBundle:Prestation:delete" }
    methods:  DELETE
