<?php

namespace DressmeBundle\Repository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends \Doctrine\ORM\EntityRepository
{
	public function findClient()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT c FROM DressmeBundle:Client c '
            )
            ->getResult();
    }

    public function counter() {
        $qb = $this->createQueryBuilder('c')
        ->select('COUNT(c)');
        return $qb->getQuery()->getSingleScalarResult();
    }
}
