<?php

namespace fb\DressmeBundle\Repository;

/**
 * EncaissementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EncaissementRepository extends \Doctrine\ORM\EntityRepository
{
		public function findEncaissement()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT e FROM DressmeBundle:Encaissement e '
            )
            ->getResult();
    }
    public function counter() {
        $qb = $this->createQueryBuilder('e')
        ->select('COUNT(e)');
        return $qb->getQuery()->getSingleScalarResult();
    }

        public function counterPrix() {
        $qb = $this->createQueryBuilder('e')
        ->select('e')
        ->leftJoin('e.prestation', 'ep')
        ->addSelect('ep')
        ->addSelect('SUM(ep.prix)');
        return $qb->getQuery()->getSingleScalarResult();
    }
}
