<?php

namespace fb\DressmeBundle\Repository;

/**
 * FicheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FicheRepository extends \Doctrine\ORM\EntityRepository
{
	public function findFiche()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT f FROM DressmeBundle:Fiche f '
            )
            ->getResult();
    }
}
